GRANT SELECT ON jazyk TO STUDENT;
GRANT SELECT ON lektori TO STUDENT;
GRANT SELECT ON se_deli_na TO STUDENT;
GRANT SELECT ON uci TO STUDENT;
GRANT SELECT ON uroven TO STUDENT;
GRANT SELECT ON zakaznici TO STUDENT;
GRANT SELECT ON zamestnanci TO STUDENT;

GRANT SELECT, DELETE, INSERT, UPDATE ON jazyk TO DB4IT218;
GRANT SELECT, DELETE, INSERT, UPDATE ON lektori TO DB4IT218;
GRANT SELECT, DELETE, INSERT, UPDATE ON se_deli_na TO DB4IT218;
GRANT SELECT, DELETE, INSERT, UPDATE ON uci TO DB4IT218;
GRANT SELECT, DELETE, INSERT, UPDATE ON uroven TO DB4IT218;
GRANT SELECT, DELETE, INSERT, UPDATE ON zakaznici TO DB4IT218;
GRANT SELECT, DELETE, INSERT, UPDATE ON zamestnanci TO DB4IT218;
